// DRUNKWATER TEMPLATE(add description and prototypes)
// Question Title and Description on leetcode.com
// Function Declaration and Function Prototypes on leetcode.com
//389. Find the Difference
//Given two strings s and t which consist of only lowercase letters.
//String t is generated by random shuffling string s and then add one more letter at a random position.
//Find the letter that was added in t.
//Example:
//Input:
//s = "abcd"
//t = "abcde"
//Output:
//e
//Explanation:
//'e' is the letter that was added.
//class Solution {
//    func findTheDifference(_ s: String, _ t: String) -> Character {
//    }
//}



// Time Is Money